# Generated by Django 6.0.3 on 2026-03-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
